server:
  port: 8010

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
    
spring:
  application:
    name: employee-service